apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demoapp
  labels:
    name: demoapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: hemrantech/flask-circleci-eks-demo:latest
        env:
        - name: FLASK_ENV
          value: "development"
      restartPolicy: Always